server:
  port: 8080
  servlet:
    context-path: /
management:
  server:
    servlet:
      context-path: /management
    port: 8081
  endpoint:
    conditions.enabled: false
    beans.enabled: false
    configprops.enabled: false
    threaddump.enabled: true
    env.enabled: false
    health.enabled: true
    info.enabled: false
    mappings.enabled: false
    metrics.enabled: true
    shutdown.enabled: false
    httptrace.enabled: false
---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db
  flyway:
    enabled: false
  jpa:
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate.integration.envers.enabled: false
logging:
  level:
    root: error